name: "Default PR Workflow"

on:
  pull_request:
  workflow_dispatch:

jobs:
  run-format-checks:
    uses: ./.github/workflows/format-check.yml
    permissions:
      pull-requests: write
      contents: read
      
  run-linting-checks:
      uses: ./.github/workflows/linting-check.yml
      permissions:
        pull-requests: write
    