name: "Default Workflow"

on:
    push:
        branches:
          - main

jobs:
    run-format-check:
        uses: ./.github/workflows/black-fmt-check.yml
        permissions:
          pull-requests: write
          contents: read

    run-linting-check:
        uses: ./.github/workflows/pylint-check.yml
        permissions:
            pull-requests: write
            contents: read

    publish-blog:
        needs:
            - run-format-check
            - run-linting-check
        uses: ./.github/workflows/publish-blog.yml
        permissions:
          pull-requests: write
          contents: read
        secrets: inherit
    