name: "Format Checks"

on:
  workflow_call:

jobs:
  py_black_fmt_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v2  # This action sets up Python
  
    - name: Install Dependencies
      run: pip install -r requirements.txt  # Install your Python dependencies
  
    - name: Format Check
      run: black --check src/
  prettier_md_fmt_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Prettier
      run: |
        npm install -g prettier

    - name: Run Prettier
      run: npx prettier --check "**/*.md"