name: "Publish Blogs - Dev.to/Medium"

on:
    push:
      branches:
        - main

jobs:
  publish_blogs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v2  # This action sets up Python
  
    - name: Install Dependencies
      run: pip install -r requirements.txt  # Install your Python dependencies
  
    - name: Publish Blog Posts
      env:
        DEVTO_API_KEY: ${{ secrets.DEVTO_API_KEY }}
        MEDIUM_API_TOKEN: ${{ secrets.MEDIUM_API_TOKEN }}
      run: python ./src/main.py